module_settings:
  module_name: "Find Company URLs"
  module_description: "Search and find LinkedIn company URLs based on criteria like industry, location, company size, or keywords. Returns a list of matching company URLs. Note: This endpoint needs verification with Icypeas documentation."
